sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^3.8.0
before_script:
  - "npm prune"
  - "npm update"
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3" # give xvfb some time to start
script:
  - npm run lint
  - npm run test
  - npm run e2e-npm
  - npm run build-package
  - npm run build-cdn
after_success:
    #  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
